cors:
  origins:
    - http://localhost:5173
    - http://127.0.0.1:5173
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowedHeaders:
    - Authorization
    - Cache-Control
    - Content-Type
