cors:
  origins:
    - https://music2pics.com/
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowedHeaders:
    - Authorization
    - Cache-Control
    - Content-Type
    - User-Agent
    - Accept
    - Origin
    - Cache-Control
    - X-Requested-With
    - Access-Control-Allow-Origin
